# Use the official Python image as the base image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy requirements file and install dependencies
RUN virtualenv venv 
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Flask app code into the container
COPY . /app

# Expose the Flask port
EXPOSE 5000

# Command to run the app
CMD ["python", "app.py"]
